### Spring properties
# Service registers under this name
spring:
  application:
    name: accounts-microservice

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 22

# Disable Spring Boot's "Whitelabel" default error page, so we can user out own
error:
  whitelabel:
    enabled: false
    